/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;



/**
 *
 * @author Beamtech
 */
public class Time extends javax.swing.JFrame {
int timeRun=0;
String Hour,Minute,second,millSec,daytime_night;
 public enum Days {
    SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
    THURSDAY, FRIDAY, SATURDAY 
}

    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
        jSpinner4.hide();
        jSpinner5.hide();
        jSpinner6.hide();
   
        new Thread(){
          public void run(){
              while(timeRun==0)
              {
                  Calendar cal = new GregorianCalendar();
                  
                  int hour = cal.get(Calendar.HOUR);
                  int minute = cal.get(Calendar.MINUTE);
                  int sec = cal.get(Calendar.SECOND);
                  int millsec = cal.get(Calendar.MILLISECOND);
                  int AM_PM = cal.get(Calendar.AM_PM);
                 int month = cal.get(Calendar.MONTH);
                 int day = cal.get(Calendar.DAY_OF_MONTH);
                 int year = cal.get(Calendar.YEAR);
                 int dayOfWeek= cal.get(Calendar.DAY_OF_WEEK);
                  if(AM_PM==1){
                     daytime_night ="PM"; 
                  } else {
                      daytime_night = "AM";
                  }
                  if(sec%2==0){
                     blink1.setText(":");
                     blink2.setText(":");
                     dayOfWeeks.setForeground(Color.cyan);
                  }else{
                    blink1.setText("");  
                    blink2.setText("");
                     dayOfWeeks.setForeground(Color.blue);
                  }
                  
                 if(dayOfWeek== 1){
                     dayOfWeeks.setText("MONDAY");
                }else if(dayOfWeek== 2){
                     dayOfWeeks.setText("TUESDAY");
                }else if(dayOfWeek== 3){
                     dayOfWeeks.setText("WENSDAY");
                }else if(dayOfWeek== 4){
                     dayOfWeeks.setText("THURSDAY");
                }else if(dayOfWeek== 5){
                     dayOfWeeks.setText("FRIDAY");
                }else if(dayOfWeek== 6){
                     dayOfWeeks.setText("SATURDAY");
                } else if(dayOfWeek== 7){
                  dayOfWeeks.setText("SUNDAY");   
                }  
                
//                Hour =( ( hour < 10 ) ? "0"+hour : hour ) + ""; 
                Hour =((hour==0)&&(AM_PM==1)? 12 : ( ( hour < 10 ) ? "0"+hour : hour ))+""; 
                
                Minute = ( ( minute < 10 ) ? "0"+ minute : minute )  + " ";
                second = ( ( sec < 10 ) ? "0"+ sec : sec )  + "";  
                millSec = millsec +"";  
               HourJlb.setText(Hour);
               MinuteJlb.setText(Minute);
               SecJlb.setText(second);
               microSecJlb.setText(millSec);
               Pm_AmJlb.setText(daytime_night);
               DateLable.setText((day)+" / "+(month+1)+" / "+year+" ");
              }
          }  
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPane = new javax.swing.JPanel();
        CloseCmd = new javax.swing.JButton();
        minimizeCmd = new javax.swing.JButton();
        HourJlb = new javax.swing.JLabel();
        SecJlb = new javax.swing.JLabel();
        MinuteJlb = new javax.swing.JLabel();
        Pm_AmJlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Alarm = new javax.swing.JPanel();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        microSecJlb = new javax.swing.JLabel();
        blink2 = new javax.swing.JLabel();
        blink1 = new javax.swing.JLabel();
        DateLable = new javax.swing.JLabel();
        dayOfWeeks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFrame");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(500, 250, 100, 150));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(100, 80));
        setType(java.awt.Window.Type.UTILITY);

        DisplayPane.setBackground(new java.awt.Color(0, 0, 0));
        DisplayPane.setForeground(new java.awt.Color(0, 168, 218));

        CloseCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close1.png"))); // NOI18N
        CloseCmd.setBorderPainted(false);
        CloseCmd.setIconTextGap(0);
        CloseCmd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CloseCmd.setMaximumSize(new java.awt.Dimension(45, 25));
        CloseCmd.setMinimumSize(new java.awt.Dimension(45, 25));
        CloseCmd.setPreferredSize(new java.awt.Dimension(45, 25));
        CloseCmd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCmdActionPerformed(evt);
            }
        });

        minimizeCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize2.png"))); // NOI18N
        minimizeCmd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeCmd.setPreferredSize(new java.awt.Dimension(18, 16));
        minimizeCmd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize1.png"))); // NOI18N
        minimizeCmd.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize1.png"))); // NOI18N
        minimizeCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeCmdActionPerformed(evt);
            }
        });

        HourJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        HourJlb.setForeground(new java.awt.Color(0, 165, 250));
        HourJlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourJlb.setText("12");
        HourJlb.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SecJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        SecJlb.setForeground(new java.awt.Color(0, 165, 250));
        SecJlb.setText("56");

        MinuteJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        MinuteJlb.setForeground(new java.awt.Color(0, 165, 250));
        MinuteJlb.setText("52");

        Pm_AmJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        Pm_AmJlb.setForeground(new java.awt.Color(0, 165, 250));
        Pm_AmJlb.setText("PM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/icons8-time-18.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Alarm.setOpaque(false);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout AlarmLayout = new javax.swing.GroupLayout(Alarm);
        Alarm.setLayout(AlarmLayout);
        AlarmLayout.setHorizontalGroup(
            AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlarmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        AlarmLayout.setVerticalGroup(
            AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlarmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        microSecJlb.setFont(new java.awt.Font("Digital-7", 1, 36)); // NOI18N
        microSecJlb.setForeground(new java.awt.Color(0, 165, 240));
        microSecJlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        microSecJlb.setText("00");

        blink2.setFont(new java.awt.Font("Digital-7", 1, 70)); // NOI18N
        blink2.setForeground(new java.awt.Color(0, 168, 218));
        blink2.setText(":");

        blink1.setFont(new java.awt.Font("Digital-7", 1, 72)); // NOI18N
        blink1.setForeground(new java.awt.Color(0, 168, 218));
        blink1.setText(":");

        DateLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DateLable.setForeground(new java.awt.Color(255, 255, 255));
        DateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLable.setText("01/01/2018");

        dayOfWeeks.setFont(new java.awt.Font("Digital-7 Mono", 1, 36)); // NOI18N
        dayOfWeeks.setForeground(new java.awt.Color(255, 255, 255));
        dayOfWeeks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfWeeks.setText("day of week");

        javax.swing.GroupLayout DisplayPaneLayout = new javax.swing.GroupLayout(DisplayPane);
        DisplayPane.setLayout(DisplayPaneLayout);
        DisplayPaneLayout.setHorizontalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(DisplayPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addComponent(HourJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(blink1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MinuteJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(blink2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Pm_AmJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(DateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(microSecJlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizeCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CloseCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addComponent(dayOfWeeks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Alarm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DisplayPaneLayout.setVerticalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(microSecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(minimizeCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CloseCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(blink2))
                    .addComponent(blink1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pm_AmJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(MinuteJlb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(HourJlb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(Alarm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dayOfWeeks, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DisplayPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCmdActionPerformed
    System.exit(0);
    }//GEN-LAST:event_CloseCmdActionPerformed

    private void minimizeCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeCmdActionPerformed
      setState(JFrame.ICONIFIED) ;     
    }//GEN-LAST:event_minimizeCmdActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    if(Alarm.isOpaque()){
             Alarm.setOpaque(false);
              Alarm.setBackground(Color.black);
              jSpinner4.setOpaque(false);
              jSpinner4.hide();
              jSpinner5.hide();
              jSpinner6.hide();
//              jSpinner1.setBackground(Color.black);
             
     }else {
         Alarm.setOpaque(true);
          Alarm.setBackground(Color.lightGray);
          jSpinner4.setOpaque(true);
          jSpinner4.setBackground(Color.LIGHT_GRAY);
          jSpinner4.show();
          jSpinner5.show();
          jSpinner6.show();
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alarm;
    private javax.swing.JButton CloseCmd;
    private javax.swing.JLabel DateLable;
    private javax.swing.JPanel DisplayPane;
    private javax.swing.JLabel HourJlb;
    private javax.swing.JLabel MinuteJlb;
    private javax.swing.JLabel Pm_AmJlb;
    private javax.swing.JLabel SecJlb;
    private javax.swing.JLabel blink1;
    private javax.swing.JLabel blink2;
    private javax.swing.JLabel dayOfWeeks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JLabel microSecJlb;
    private javax.swing.JButton minimizeCmd;
    // End of variables declaration//GEN-END:variables
}
