/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;



/**
 *
 * @author Beamtech
 */
public class Time extends javax.swing.JFrame {
int timeRun=0;
String Hour,Minute,second,millSec,daytime_night;

    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
        new Thread(){
          public void run(){
              while(timeRun==0)
              {
                  Calendar cal = new GregorianCalendar();
                  
                  int hour = cal.get(Calendar.HOUR);
                  int minute = cal.get(Calendar.MINUTE);
                  int sec = cal.get(Calendar.SECOND);
                  int millsec = cal.get(Calendar.MILLISECOND);
                  int AM_PM = cal.get(Calendar.AM_PM);
                 int month = cal.get(Calendar.DATE);
                  if(AM_PM==1){
                     daytime_night ="PM"; 
                  } else {
                      daytime_night = "AM";
                  }
                  if(sec%2==0){
                     blink1.setText(":");
                     blink2.setText(":");
                  }else{
                    blink1.setText("");  
                    blink2.setText("");
                  }
                 
//                Hour =( ( hour < 10 ) ? "0"+hour : hour ) + ""; 
                Hour =((hour==0)&&(AM_PM==1)? 12 : ( ( hour < 10 ) ? "0"+hour : hour ))+""; 
                
                Minute = ( ( minute < 10 ) ? "0"+ minute : minute )  + " ";
                second = ( ( sec < 10 ) ? "0"+ sec : sec )  + "";  
                millSec = millsec +"";  
               HourJlb.setText(Hour);
               MinuteJlb.setText(Minute);
               SecJlb.setText(second);
               microSecJlb.setText(millSec);
               Pm_AmJlb.setText(daytime_night);
              }
          }  
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPane = new javax.swing.JPanel();
        CloseCmd = new javax.swing.JButton();
        minimizeCmd = new javax.swing.JButton();
        HourJlb = new javax.swing.JLabel();
        SecJlb = new javax.swing.JLabel();
        MinuteJlb = new javax.swing.JLabel();
        Pm_AmJlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Alarm = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        microSecJlb = new javax.swing.JLabel();
        blink2 = new javax.swing.JLabel();
        blink1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFrame");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(500, 250, 100, 150));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(100, 80));
        setType(java.awt.Window.Type.UTILITY);

        DisplayPane.setBackground(new java.awt.Color(0, 0, 0));
        DisplayPane.setForeground(new java.awt.Color(0, 168, 218));

        CloseCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close1.png"))); // NOI18N
        CloseCmd.setBorderPainted(false);
        CloseCmd.setIconTextGap(0);
        CloseCmd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CloseCmd.setMaximumSize(new java.awt.Dimension(45, 25));
        CloseCmd.setMinimumSize(new java.awt.Dimension(45, 25));
        CloseCmd.setPreferredSize(new java.awt.Dimension(45, 25));
        CloseCmd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/close2.png"))); // NOI18N
        CloseCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCmdActionPerformed(evt);
            }
        });

        minimizeCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize2.png"))); // NOI18N
        minimizeCmd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeCmd.setPreferredSize(new java.awt.Dimension(18, 16));
        minimizeCmd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize1.png"))); // NOI18N
        minimizeCmd.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/mimimize1.png"))); // NOI18N
        minimizeCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeCmdActionPerformed(evt);
            }
        });

        HourJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        HourJlb.setForeground(new java.awt.Color(0, 165, 250));
        HourJlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourJlb.setText("12");
        HourJlb.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SecJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        SecJlb.setForeground(new java.awt.Color(0, 165, 250));
        SecJlb.setText("56");

        MinuteJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        MinuteJlb.setForeground(new java.awt.Color(0, 165, 250));
        MinuteJlb.setText("52");

        Pm_AmJlb.setFont(new java.awt.Font("Digital-7", 1, 48)); // NOI18N
        Pm_AmJlb.setForeground(new java.awt.Color(0, 165, 250));
        Pm_AmJlb.setText("PM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital/icons8-time-18.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Alarm.setOpaque(false);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        jSpinner1.setOpaque(false);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout AlarmLayout = new javax.swing.GroupLayout(Alarm);
        Alarm.setLayout(AlarmLayout);
        AlarmLayout.setHorizontalGroup(
            AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlarmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        AlarmLayout.setVerticalGroup(
            AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlarmLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(AlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        microSecJlb.setFont(new java.awt.Font("Digital-7", 1, 36)); // NOI18N
        microSecJlb.setForeground(new java.awt.Color(0, 165, 240));
        microSecJlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        microSecJlb.setText("00");

        blink2.setFont(new java.awt.Font("Digital-7", 1, 70)); // NOI18N
        blink2.setForeground(new java.awt.Color(0, 168, 218));
        blink2.setText(":");

        blink1.setFont(new java.awt.Font("Digital-7", 1, 72)); // NOI18N
        blink1.setForeground(new java.awt.Color(0, 168, 218));
        blink1.setText(":");

        javax.swing.GroupLayout DisplayPaneLayout = new javax.swing.GroupLayout(DisplayPane);
        DisplayPane.setLayout(DisplayPaneLayout);
        DisplayPaneLayout.setHorizontalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisplayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Alarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisplayPaneLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(186, 186, 186)
                            .addComponent(microSecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(minimizeCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CloseCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addComponent(HourJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(blink1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MinuteJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(blink2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Pm_AmJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DisplayPaneLayout.setVerticalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPaneLayout.createSequentialGroup()
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayPaneLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(microSecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CloseCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(minimizeCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)))
                .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(blink2))
                    .addGroup(DisplayPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blink1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SecJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pm_AmJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(MinuteJlb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(HourJlb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, 0)
                .addComponent(Alarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DisplayPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCmdActionPerformed
    System.exit(0);
    }//GEN-LAST:event_CloseCmdActionPerformed

    private void minimizeCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeCmdActionPerformed
      setState(JFrame.ICONIFIED) ;     
    }//GEN-LAST:event_minimizeCmdActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    if(Alarm.isOpaque()){
             Alarm.setOpaque(false);
              Alarm.setBackground(Color.black);
              jSpinner1.setOpaque(false);
              jSpinner1.hide();
              jSpinner2.hide();
              jSpinner3.hide();
//              jSpinner1.setBackground(Color.black);
             
     }else {
         Alarm.setOpaque(true);
          Alarm.setBackground(Color.lightGray);
          jSpinner1.setOpaque(true);
          jSpinner1.setBackground(Color.LIGHT_GRAY);
          jSpinner1.show();
          jSpinner2.show();
          jSpinner3.show();
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alarm;
    private javax.swing.JButton CloseCmd;
    private javax.swing.JPanel DisplayPane;
    private javax.swing.JLabel HourJlb;
    private javax.swing.JLabel MinuteJlb;
    private javax.swing.JLabel Pm_AmJlb;
    private javax.swing.JLabel SecJlb;
    private javax.swing.JLabel blink1;
    private javax.swing.JLabel blink2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JLabel microSecJlb;
    private javax.swing.JButton minimizeCmd;
    // End of variables declaration//GEN-END:variables
}
